#!/bin/bash

project_file_path="./src/Ksu.Gdc.Api.Web/Ksu.Gdc.Api.Web.csproj"

if [ -z $1 ]; then
    echo "ERROR :- 1st argument required - target runtime to publish for"
    exit 1
fi
output_dir=$1
if [ ! -z $2 ]; then
    if [ $2 == *"/"* ]; then
        echo "ERROR :- 2nd argument invalid - output directory cannot have '/'"
        exit 1
    fi
    output_dir=$2
fi

dotnet restore -r $1 $project_file_path
if [ $? -ne 0 ]; then
    exit $?
fi
dotnet build -r $1 $project_file_path
if [ $? -ne 0 ]; then
    exit $?
fi
dotnet publish -r $1 -c Release -o ./Releases/$output_dir $project_file_path
