// <auto-generated />
using System;
using Ksu.Gdc.Api.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ksu.Gdc.Api.Data.Migrations
{
    [DbContext(typeof(KsuGdcContext))]
    [Migration("20181225200149_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 12, 25, 14, 1, 49, 708, DateTimeKind.Unspecified).AddTicks(730), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("HostUrl")
                        .HasMaxLength(2000);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 12, 25, 14, 1, 49, 708, DateTimeKind.Unspecified).AddTicks(1210), new TimeSpan(0, -6, 0, 0, 0)));

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_GameUser", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("GameId");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 12, 25, 14, 1, 49, 710, DateTimeKind.Unspecified).AddTicks(3030), new TimeSpan(0, -6, 0, 0, 0)));

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GameUsers");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 12, 25, 14, 1, 49, 696, DateTimeKind.Unspecified).AddTicks(4430), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 12, 25, 14, 1, 49, 707, DateTimeKind.Unspecified).AddTicks(2090), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<int?>("UserId");

                    b.HasKey("OfficerId");

                    b.HasIndex("UserId");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 12, 25, 14, 1, 49, 707, DateTimeKind.Unspecified).AddTicks(6520), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 12, 25, 14, 1, 49, 707, DateTimeKind.Unspecified).AddTicks(7030), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_GameUser", b =>
                {
                    b.HasOne("Ksu.Gdc.Api.Data.Entities.DbEntity_Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ksu.Gdc.Api.Data.Entities.DbEntity_User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_Officer", b =>
                {
                    b.HasOne("Ksu.Gdc.Api.Data.Entities.DbEntity_User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
