// <auto-generated />
using System;
using Ksu.Gdc.Api.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ksu.Gdc.Api.Data.Migrations
{
    [DbContext(typeof(KsuGdcContext))]
    [Migration("20181025070932_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.JoinEntity_UserGroup", b =>
                {
                    b.Property<int>("UserGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<int>("GroupId");

                    b.Property<int>("UserId");

                    b.HasKey("UserGroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.ModelEntity_Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<int?>("GroupId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("ItemUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.Property<int?>("UserId");

                    b.HasKey("GameId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.ModelEntity_Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.ModelEntity_Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.Property<int?>("UserId");

                    b.HasKey("OfficerId");

                    b.HasIndex("UserId");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.ModelEntity_User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.JoinEntity_UserGroup", b =>
                {
                    b.HasOne("Ksu.Gdc.Api.Data.Entities.ModelEntity_Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ksu.Gdc.Api.Data.Entities.ModelEntity_User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.ModelEntity_Game", b =>
                {
                    b.HasOne("Ksu.Gdc.Api.Data.Entities.ModelEntity_Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Ksu.Gdc.Api.Data.Entities.ModelEntity_User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.ModelEntity_Officer", b =>
                {
                    b.HasOne("Ksu.Gdc.Api.Data.Entities.ModelEntity_User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
