// <auto-generated />
using System;
using Ksu.Gdc.Api.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ksu.Gdc.Api.Data.Migrations
{
    [DbContext(typeof(KsuGdcContext))]
    [Migration("20181031062825_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 560, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<int?>("GroupId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 560, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.Property<string>("Url")
                        .IsRequired();

                    b.Property<int?>("UserId");

                    b.HasKey("GameId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 551, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 551, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_GroupUser", b =>
                {
                    b.Property<int>("GroupId");

                    b.Property<int>("UserId");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 560, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 560, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupUsers");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 535, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 550, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.Property<int?>("UserId");

                    b.HasKey("OfficerId");

                    b.HasIndex("UserId");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 550, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2018, 10, 31, 1, 28, 25, 551, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)));

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_Game", b =>
                {
                    b.HasOne("Ksu.Gdc.Api.Data.Entities.DbEntity_Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Ksu.Gdc.Api.Data.Entities.DbEntity_User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_GroupUser", b =>
                {
                    b.HasOne("Ksu.Gdc.Api.Data.Entities.DbEntity_Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ksu.Gdc.Api.Data.Entities.DbEntity_User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ksu.Gdc.Api.Data.Entities.DbEntity_Officer", b =>
                {
                    b.HasOne("Ksu.Gdc.Api.Data.Entities.DbEntity_User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
