#!/bin/bash
# $1 - argument - number of migrations to remove or "all"

if [ -z "$1" ]; then
	echo "Number of migrations or \"all\" must be specified"
        exit
fi
if [ $1 == "all" ]; then
	echo "Removing all migrations ..."
elif [ $1 -eq 1 ]; then
	echo "Removing $1 migration ..."
elif [ $1 -gt 1 ]; then
	echo "Removing $1 migrations ..."
else
	echo "Number of migrations to remove must be >= 1 or \"all\"."
	exit
fi

i=1
num=1
if [ $1 == "all" ]; then
	max=1
else
	max=$1
fi
while [ $i -le $max ]; do
	dotnet ef migrations remove -p Ksu.Gdc.Api.Data -s Ksu.Gdc.Api.Web
	if [ $? -eq 0 ]; then
		if [ $num -eq 1 ]; then
			echo "$num migration removed."
		else
			echo "$num migrations removed."
		fi
	else
		break
	fi
	num=$(($num + 1))
	if [ $1 != "all" ]; then
		i=$(($i + 1))
	fi
done
