#!/bin/bash
# $1 -> argument - name of migration

echo "Adding migration \"$1\" ..."

dotnet ef migrations add -p Ksu.Gdc.Api.Data -s Ksu.Gdc.Api.Web "$1"
if [ $? -eq 0 ]; then
	echo "Migration \"$1\" created."
fi
